version: "3.8"

services:
  app:
    build:
      context: .
      target: backend
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - $PWD:/app
    command: flask run
